replicaCount: 1

server:
  name: localhost
  baseURL: http://localhost
  port: 30009

image:
  repository: custom/element
  tag: v1.0.0
  pullPolicy: Never

containers:
  containerPort: 80

livenessProbe:
  path: /
  port: 80
  initialDelaySeconds: 10
  periodSeconds: 10

service:
  type: NodePort
  port: 80

ingress:
  enabled: true
  className: ""
  annotations:
    kubernetesIoIngressClass: nginx
  hosts:
    host: localhost
    paths:
      path: /
      pathType: Prefix
