apiVersion: apps/v1
kind: Deployment
metadata:
    name: element
spec:
    selector:
        matchLabels:
            app: element
    replicas: 1
    template:
        metadata:
            labels:
                app: element
        spec:
            containers:
                - name: element
                  image: custom/element-web:v1.0.0
                  imagePullPolicy: Never
                  volumeMounts:
                      - name: config-volume
                        readOnly: true
                        mountPath: /app/config.json
                        subPath: config.json
                  ports:
                      - containerPort: 80
                        name: element
                        protocol: TCP
                  livenessProbe:
                      httpGet:
                          path: /
                          port: element
                      initialDelaySeconds: 10
                      periodSeconds: 10
            volumes:
                - name: config-volume
                  configMap:
                      name: element-config
