apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-cm
data:
  dendrite.yaml: |-
{{ .Files.Get "dendrite.yaml" | indent 4 }}
  matrix_key.pem: |-
{{ .Files.Get "matrix_key.pem" | indent 4 }}
