apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      {{- if .Release.IsInstall }}
      initContainers:
        - name: generate-signing-key
          image: "golang:1.17-alpine"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["sh"]
          args:
            - "-c"
            - "go install github.com/matrix-org/dendrite/cmd/generate-keys@latest && generate-keys --private-key=/etc/dendrite/matrix_key.pem --tls-cert=/etc/dendrite/server.crt --tls-key=/etc/dendrite/server.key"
          env:
            - name: GOCACHE
              value: "/go/.cache"
          volumeMounts:
            - name: keys
              mountPath: /etc/dendrite/
      {{- end }}
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag | default "v0.5.0" }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: config
              mountPath: /etc/dendrite/dendrite.yaml
              subPath: dendrite.yaml
            - name: keys
              mountPath: /etc/dendrite/
          ports:
            - name: cs
              containerPort: {{ .Values.deployments.containers.containerPort.http }}
              protocol: TCP
            - name: federation
              containerPort: {{ .Values.deployments.containers.containerPort.https }}
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            httpGet:
              path: {{ .path }}
              port: {{ .port }}
            initialDelaySeconds: {{ .initialDelaySeconds }}
            periodSeconds: {{ .periodSeconds }}
          {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}-cm
        - name: keys
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-pvc
