apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{.Release.Name}}-pv
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: {{ .Values.volume.storage }}
  hostPath:
    path: "/etc/dendrite/"
