replicaCount: 1

deployments:
  containers:
    containerPort:
      hhtp: 8008
      https: 8448

image:
  repository: matrixdotorg/dendrite-monolith
  pullPolicy: IfNotPresent
  tag: v0.5.1

service:
  type: ClusterIP
  ports:
    http: 8008
    https: 8448
