replicaCount: 1

serverName: dendrite-svc

deployments:
  containers:
    containerPort:
      http: 8008
      https: 8448

image:
  repository: matrixdotorg/dendrite-monolith
  pullPolicy: IfNotPresent
  tag: v0.5.1

service:
  type: NodePort
  ports:
    http: 8008
    https: 8448
  nodePorts:
    http: 30009

volume:
  storage: 200Mi
  claime:
    storage: 50Mi
